### ISSUE TITLE
network error for rstudio-server on waldronlab/bioconductor

### ISSUE THREAD

**Issue by lwaldron** [databio/bulker#36]
I'm using the `waldronlab/bioconductor` manifest on hub.bulker.io, the config file at https://github.com/waldronlab/config/blob/master/bulker_config.yaml, and have updated my `templates/docker_executable.jinja2` and `templates/docker_shell.jinja2` to the ones on the dev branch (https://github.com/databio/bulker/tree/dev/bulker/templates). Now when I launch `rstudio-dev`, I don't get any errors:

```
Levis-MBP:~ lwaldron$ bulker activate waldronlab/bioconductor
Bulker config: /Users/lwaldron/bulker_config.yaml
Activating bulker crate: waldronlab/bioconductor

bulker-3.2$ cat `which rstudio-server`
#!/bin/sh

docker run --rm --init \
  --volume=/Users/lwaldron/R/bioc-release:/usr/local/lib/R/host-site-library -e PASSWORD=rstudiopassword -p 8787:8787 \
  --env "DISPLAY" \
  --volume "/tmp:/tmp" \
  --volume "$HOME:$HOME" \
  --workdir="`pwd`" \
  bioconductor/bioconductor_full:release   "$@"
bulker-3.2$ rstudio-server
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] add: executing... 
Nothing additional to add
[cont-init.d] add: exited 0.
[cont-init.d] userconf: executing... 
[cont-init.d] userconf: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

However, when I try to use the rstudio server in my web browser at http://localhost:8787, I get an error "RStudio initialization error": "Error occurred during transmission". I noted that when I instead browsed to http://0.0.0.0:8787, rstudio did give me a login page, but after authentiating I got the same error. I couldn't reproduce that behavior, however: on subsequent launches, even after shutting down the rstudio process and restarting bulker, I got the "Error occurred during transmission" right away when browsing to either URL.

**Comment by nsheff** [comment]
can you figure out what in the docker file is causing the problem? That docker file is only slightly different from the way you are executing it that works... try taking out the --workdir or the --env variables and see if it's one of those things

just running that docker command directly to test will work

**Comment by nsheff** [comment]
could also be the `--init`? 

By the way, that docker command works correctly for me; rstudioserver is loaded and authenticates correctly.

**Comment by lwaldron** [comment]
This seems hard to believe, but the only thing I have to remove to avoid the network error is:

```
  --volume "/tmp:/tmp" \
```

So a working rstudio-server file looks like this:
```
#!/bin/sh                                                                                                                                                                

docker run --rm --init \
  --volume=/Users/lwaldron/R/bioc-release:/usr/local/lib/R/host-site-library -e PASSWORD=rstudiopassword -p 8787:8787 \
  --env "DISPLAY" \
  --volume "$HOME:$HOME" \
  --workdir="`pwd`" \
  bioconductor/bioconductor_full:release   "$@"
```

**Comment by nsheff** [comment]
I cannot explain that but maybe I'll look into it later this week. 

but what that means is the solution for you is to remove the `/tmp` from your volumes section in the bulker config file... I don't think we need it for anything specifically, actually, so I'll just remove it from the demo template. It was mostly just in there as an example, actually, that has just persisted, because I thought it might be useful for something...

I don't know if I want to go down the route of specifying 'exclude volumes', but I guess I could, if `/tmp` needs to be present for all the other containers...

**Comment by lwaldron** [comment]
Just confirming that I reproduced this behavior on a second OSX machine. Network error with `volumes: ['$HOME','/tmp']` in my bulker_config.yaml, but no problem starting rstudio-server with `volumes: ['$HOME']` (after doing bulker load and activate again). I have no need at this point to 'exclude volumes', just not mounting /tmp is good enough for me.

**Comment by nsheff** [comment]
I've been poking around at this and I cannot find any immediate reason why this would be a problem, specifically on mac. It has either to do with the way rstudio is set up to use /tmp, or the way the rocker pages are using the s6 init system, or something. In any case, since this is an edge case and we have an acceptable workaround, I'm going to close this issue rather than continue to try to figure it out. I will remove the /tmp from the default config.
